create database Students_data;
use Students_Data;
create table Students(id int primary key, Name varchar(100), age int, grade int, city varchar(100));
select * from students;
insert into students values (1, 'Alice', 17, 88, 'Mumbai'), (2, 'Bob', 18, 92, 'Delhi'),(3, 'Charlie', 17,75,'Kolkata'), (4,'David', 18,85,'Mumbai'),(5,'Eva',16,91,'Chennai');
select * from students where city='mumbai';
select name from students where grade > 90;
select * from students order by grade desc;
select city, count(*) from students group by city;
create table courses(student_id int, course varchar(100), score int);
insert into courses values(1,'Math', 80),(2,'Science', 90), (3,'History', 70), (1,'Science',85), (5,'Math', 95);
drop table courses;
select * from courses;
select courses.score, students.grade from courses join students on courses.student_id=students.id;